# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
